export CUDA_VISIBLE_DEVICES=3
python -m torch.distributed.launch --nproc_per_node=1 --master_port=12334 --use_env run_train.py \
--diff_steps 2000 \
--lr 0.0001 \
--learning_steps 50000 \
--save_interval 2000 \
--seed 6868 \
--noise_schedule sqrt \
--hidden_dim 128 \
--bsz 200 \
--microbatch 200 \
--dataset qqp \
--data_dir ./datasets/QQP-Official \
--vocab qwen \
--seq_len 128 \
--schedule_sampler lossaware \
--resume_checkpoint "None" \
--notes qqp-qwen \
--sc_rate 0.5 \
--rescale_max 1000 \
--config_name /vepfs/jinke/bw-data/FMSeq0/models/Qwen3-0.6B